name = "bettershift-telemetry-hub"
main = "src/index.ts"
compatibility_date = "2026-09-18"

routes = [
  { pattern = "telemetry-bettershift.pantelx.com", custom_domain = true, zone_name = "pantelx.com", enabled = true, previews_enabled = false }
]

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "bettershift_telemetry"
database_name = "bettershift-telemetry"
database_id = "79d67a9c-d7bc-4514-af1e-f24dd1a94e24"
migrations_dir = "migrations"
